### ISSUE TITLE
erreur sur la méthode getMasterRequest()

### ISSUE THREAD

**Issue by Xipotera** [fungio/FungioOutlookCalendarBundle#1]
Bonjour, 
j'ai essayé de mettre en place ton bundle mais a priori il me manque la méthode ```getMasterRequest()```!
Je pense qu'il me manque un petit use ou quelque chose du genre.

Pourrez tu mettres à dispo un exemple de base ou me donner un petit coup de main pour finir mon test.

Merci d'avance.

**Comment by fungio** [comment]
En effet je me suis trompé dans la doc
`<?php
$request = $this->get('request_stack')->getMasterRequest();`

**Comment by Xipotera** [comment]
merci pour la rapidité de ta réponse ;)
du coup une autre erreur, la variable ```$redirectUri``` apparait comme indefinit!

**Comment by fungio** [comment]
Ouais il faut initialiser `$redirectUri` avec l'url de ton serveur, la même que tu as déclaré sur la plateforme microsoft (https://apps.dev.microsoft.com)

**Comment by fungio** [comment]
Si tu travail en local, il faut que l'url soit http://localhost car leur plateforme n'accepte pas de virtualhost.

**Comment by Xipotera** [comment]
en effet, j'avais trouvé la solution. 
Merci toutefois pour la réponse
