### ISSUE TITLE
Au sujet des calendriers partagés?

### ISSUE THREAD

**Issue by Xipotera** [fungio/FungioOutlookCalendarBundle#2]
Bonjour, 
je me suis bien amusé hier à tester ton bundle et tout fonctionne nickel.
Par contre, peux tu me renseigner au sujet des calendriers partagés savoir s'il est possible de récupérer les événements d'un autre collaborateur.
J'ai regardé du coté de la description de l'api mes rien de concluant!!

Si jamais tu n'as pas était confronté à ce soucis, je te communiquerais le résultat de mes recherches.

Merci de tes retours!

**Comment by fungio** [comment]
D'après la doc tu peux récuperer tous les calendrier avec : 
`GET https://outlook.office.com/api/v2.0/me/calendars`

Après dans la requete qui récupere les évenements tu peux spécifier le calendrier 
`https://outlook.office.com/api/v2.0/me/calendars/{calendar_id}`

**Comment by fungio** [comment]
J'ai mis a jour le code (ba79f188a9fd5b50ff2b5026e618664330e88c49) il y a une fonction pour récupérer les calendriers getCalendars qui devrait en théorie renvoyer un array avec l'ID des calendriers. Après tu peux passer cet ID dans l'une des 2 fonctions getEventsOnRange ou getEventsForDate

**Comment by Xipotera** [comment]
je te remercie pour ta réactivité, je regarde ça dès que possible et te tiens au courant.
